name: "Test Api Trigger"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: HTTP Request Action
      run: |
        curl 'http://52.221.113.44/items/5\?q\=helll'
