name: "Test Api Trigger"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Build ARM64 Docker Image
      run: |
          curl -X POST http://52.221.113.44/build-arm -H 'Content-type: application/json' \
          -d '{"docker_repository": "soo0123/testx","git_repository": "mztesting","image_name": "soo0123/testx:v1","git_tag":"actiontesting5"}'
